
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-foo-config
data:
  foo.go: |-
    package main
    
    import (
        "fmt"
        "time"
    )
    
    func main() {
        for {
            fmt.Println("Hello world!")
            time.Sleep(30 * time.Second)
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-foo-deploy
  labels:
    app: go-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-foo
  template:
    metadata:
      labels:
        app: go-foo
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: go-foo-config
      containers:
      - name: go-foo
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/go-docker:go1.15
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/src
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          go build -o /tmp/main /tmp/src/foo.go &&
          /tmp/main


