
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/web:v1.0.91
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: web-service-80-80
    port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-deploy
  labels:
    app: versions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: versions
  template:
    metadata:
      labels:
        app: versions
    spec:
      containers:
        - name: versions
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/versions:v1.0.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: versions-service
spec:
  type: ClusterIP
  selector:
    app: versions
  ports:
  - name: versions-service-9000-9000
    port: 9000
    protocol: TCP
    targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-terraform-deploy
  labels:
    app: srs-terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-terraform
  template:
    metadata:
      labels:
        app: srs-terraform
    spec:
      containers:
        - name: releases
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:releases-v1.0.237
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: srs-terraform-service
spec:
  type: ClusterIP
  selector:
    app: srs-terraform
  ports:
  - name: srs-terraform-service-9000-9000
    port: 9000
    protocol: TCP
    targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgsw-deploy
  labels:
    app: hgsw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgsw
  template:
    metadata:
      labels:
        app: hgsw
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: hgsw-config
      containers:
        - name: hgsw
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/hgsw:v1.0.11
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          command: ["./bin/http-gif-sls-writer", "-c", "./etc/main.conf"]
          ports:
            - containerPort: 1987
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc

---

apiVersion: v1
kind: Service
metadata:
  name: hgsw-tcp-service
spec:
  type: ClusterIP
  selector:
    app: hgsw
  ports:
  - name: hgsw-tcp-service-1987-1987
    port: 1987
    protocol: TCP
    targetPort: 1987

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deploy
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/docs:cn-v1.0.27
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          command: ["./bin/httpx-static", "-http", "80", "-root", "./srs-docs"]
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: docs-tcp-service
spec:
  type: ClusterIP
  selector:
    app: docs
  ports:
  - name: docs-tcp-service-80-80
    port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense-deploy
  labels:
    app: typesense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: srs-docs
      containers:
        ###################################################################################################
        - name: typesense
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/typesense:0.22.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          # Secret, type: Opaque, name: srs-docs, key: search-api-key
          env:
          - name: SEARCH_APIKEY
            valueFrom:
              secretKeyRef:
                name: srs-docs
                key: search-api-key
          # To store data in the volume.
          volumeMounts:
          - name: cache-volume
            mountPath: /data
            readOnly: false
          # Startup args.
          args: ["--enable-cors", "--data-dir", "/data", "--api-key", "$(SEARCH_APIKEY)"]
          ports:
          - containerPort: 8108
        ###################################################################################################
        - name: scraper
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/docsearch-scraper:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: UPDATE_NB_HITS
              value: "0"
            - name: TYPESENSE_HOST
              value: typesense-for-scraper
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: srs-docs
                  key: search-api-key
            - name: TYPESENSE_PORT
              value: "8108"
            - name: TYPESENSE_PROTOCOL
              value: http
            - name: CONFIG
              value: /conf/srs-docs-search-config.json
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              pipenv run python -m src.index;
              echo "Search scraper OK";
              sleep infinity;
          volumeMounts:
            - name: config-volume
              mountPath: /conf

---

apiVersion: v1
kind: Service
metadata:
  name: typesense-tcp-service
spec:
  type: ClusterIP
  selector:
    app: typesense
  ports:
  - name: typesense-tcp-service-8108-8108
    port: 8108
    protocol: TCP
    targetPort: 8108

---

apiVersion: v1
kind: Service
metadata:
  name: typesense-for-scraper
spec:
  clusterIP: None
  selector:
    app: typesense
  ports:
  - name: typesense-for-scraper-8108-8108
    port: 8108
    protocol: TCP
    targetPort: 8108

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpx-web-deploy
  labels:
    app: httpx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpx-web
  template:
    metadata:
      labels:
        app: httpx-web
    spec:
      volumes:
        - name: ssl-volume
          configMap:
            name: ossrs.net
      containers:
        - name: httpx-web
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/httpx:v1.0.21
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 200m
              memory: 200Mi
          command: ["/bin/sh"]
          args:
          - "-c"
          - >
            ./bin/httpx-static
            -http=80
            -https=443 -https=8443 -lets=false
            -sdomain ossrs.net -skey ./etc/ossrs.net.key -scert ./etc/ossrs.net.pem
            -sdomain www.ossrs.net -skey ./etc/ossrs.net.key -scert ./etc/ossrs.net.pem
            -sdomain api.ossrs.net -skey ./etc/api.ossrs.net.key -scert ./etc/api.ossrs.net.pem
            -proxy=http://r.ossrs.net:1985/api/v1/
            -proxy=http://r.ossrs.net:1985/rtc/v1/
            -proxy=http://webrtc-signaling-service:8888/api/webrtc/
            -proxy=http://hgsw-tcp-service:1987/gif/v1
            -proxy=http://versions-service:9000/service/v1/?modifyRequestHost=true
            -pre-hook=http://hgsw-tcp-service:1987/service/v1/?_sys_logstore=srs-eggs\&_sys_logfmt_app=true\&_sys_keep_ua=false\&_sys_keep_referer=false\&_sys_keep_oreferer=false\&_sys_keep_oua=false\&_sys_keep_fwd=false
            -proxy=http://srs-terraform-service:9000/terraform/v1/?modifyRequestHost=true
            -pre-hook=http://hgsw-tcp-service:1987/terraform/v1/?_sys_logstore=cloud-eggs\&_sys_logfmt_app=true\&_sys_keep_ua=false\&_sys_keep_referer=false\&_sys_keep_oreferer=false\&_sys_keep_oua=false\&_sys_keep_fwd=false
            -proxy=http://service-cfc43k8y-1303949587.gz.apigw.tencentcs.com/ffmpeg/?modifyRequestHost=true\&trimPrefix=/ffmpeg\&addPrefix=/release
            -proxy=http://docs-tcp-service:80/lts/
            -proxy=http://typesense-tcp-service:8108/multi_search
            -proxy=http://web-service:80/
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: ssl-volume
              mountPath: /usr/local/etc

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-2ze2nh2hevqwe1nzlpx4g
  name: httpx-web-service
spec:
  type: LoadBalancer
  # Must set to Local to get the client real IP.
  # https://www.alibabacloud.com/help/zh/doc-detail/86531.htm
  externalTrafficPolicy: Local
  selector:
    app: httpx-web
  ports:
    - name: httpx-web-service-80-80
      port: 80
      protocol: TCP
      targetPort: 80
    - name: httpx-web-service-8000-80
      port: 8000
      protocol: TCP
      targetPort: 80
    - name: httpx-web-service-1985-80
      port: 1985
      protocol: TCP
      targetPort: 80
    - name: httpx-web-service-443-443
      port: 443
      protocol: TCP
      targetPort: 443
    - name: httpx-web-service-8443-443
      port: 8443
      protocol: TCP
      targetPort: 443
