
apiVersion: v1
kind: ConfigMap
metadata:
  name: srs4-config
data:
  srs.conf: |-
    listen              1935;
    max_connections     1000;
    daemon              off;
    http_api {
        enabled         on;
        listen          1985;
    }
    http_server {
        enabled         on;
        listen          8080;
    }
    rtc_server {
      enabled         on;
      listen          8000;
      # Firefox doesn't work with domain.
      #candidate       r.ossrs.net;
      candidate       39.107.238.185;
    }
    vhost __defaultVhost__ {
        rtc {
            enabled     on;
            rtmp_to_rtc on;
            rtc_to_rtmp on;
        }
        http_remux {
            enabled     on;
        }
        hls {
            enabled     on;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs4-deploy
  labels:
    app: srs4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs4
  template:
    metadata:
      labels:
        app: srs4
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: srs4-config
      containers:
      - name: srs4
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:v4.0-b10
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
        - containerPort: 8000
          name: udp-service
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/srs/conf

---

apiVersion: v1
kind: Service
metadata:
  name: srs4-service
spec:
  type: ClusterIP
  selector:
    app: srs4
  ports:
  - name: srs4-service-1935-1935
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: srs4-service-1985-1985
    port: 1985
    protocol: TCP
    targetPort: 1985
  - name: srs4-service-8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs4-demo-deploy
  labels:
    app: srs4-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs4-demo
  template:
    metadata:
      labels:
        app: srs4-demo
    spec:
      containers:
      - name: livestream
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:encoder
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 400Mi
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          while true; do
            ffmpeg -re -i ./doc/winlin.300kbps.640x360.baseline.flv -c copy \
              -f flv rtmp://srs4-service:1935/live/livestream && continue;
            sleep 3;
          done
      - name: bbb
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:encoder
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 400Mi
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          while true; do
            ffmpeg -re -i ./doc/bbb.300kbps.640x360.baseline.flv -c copy \
              -f flv rtmp://srs4-service:1935/live/bbb && continue;
            sleep 3;
          done
      - name: avatar
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:encoder
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 400Mi
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          while true; do
            ffmpeg -re -i ./doc/source.200kbps.768x320.flv -c copy \
              -f flv rtmp://srs4-service:1935/live/avatar && continue;
            sleep 3;
          done

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpx-rsrs-deploy
  labels:
    app: httpx-rsrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpx-rsrs
  template:
    metadata:
      labels:
        app: httpx-rsrs
    spec:
      volumes:
      - name: ssl-volume
        configMap:
          name: r.ossrs.net
      containers:
      - name: httpx-rsrs
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/httpx:v1.0.18
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 200Mi
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          ./bin/httpx-static
          -http=80 -https=443 -lets=false
          -sdomain r.ossrs.net -skey ./etc/r.ossrs.net.key -scert ./etc/r.ossrs.net.pem
          -proxy=http://srs4-service:1985/rtc/
          -proxy=http://srs4-service:1985/api/
          -proxy=http://sig-service:1989/sig/
          -proxy=http://srs4-service:8080/
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: ssl-volume
          mountPath: /usr/local/etc

---

# SLB for r.ossrs.net
# https://slb.console.aliyun.com/slb/cn-beijing/slbs/lb-2zetmjpao868s9yzvr5ld/listeners
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-2zetmjpao868s9yzvr5ld
  name: srs4-tcp-service
spec:
  type: LoadBalancer
  selector:
    app: srs4
  ports:
    - name: srs4-service-1935-1935
      port: 1935
      protocol: TCP
      targetPort: 1935

---

# SLB for r.ossrs.net
# https://slb.console.aliyun.com/slb/cn-beijing/slbs/lb-2zetmjpao868s9yzvr5ld/listeners
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-2zetmjpao868s9yzvr5ld
  name: httpx-rsrs-service
spec:
  type: LoadBalancer
  selector:
    app: httpx-rsrs
  ports:
  - name: httpx-rsrs-service-1985-80
    port: 1985
    protocol: TCP
    targetPort: 80
  - name: httpx-rsrs-service-8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: httpx-rsrs-service-80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: httpx-rsrs-service-443-443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: httpx-rsrs-service-8443-443
    port: 8443
    protocol: TCP
    targetPort: 443
  - name: httpx-rsrs-service-8088-443
    port: 8088
    protocol: TCP
    targetPort: 443

---

# SLB for r.ossrs.net
# https://slb.console.aliyun.com/slb/cn-beijing/slbs/lb-2zetmjpao868s9yzvr5ld/listeners
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-2zetmjpao868s9yzvr5ld
  name: srs4-udp-service
spec:
  type: LoadBalancer
  selector:
    app: srs4
  ports:
  - name: srs4-udp-service-8000-8000
    port: 8000
    protocol: UDP
    targetPort: 8000

